enum ClientPermission {
  CREATE_CLIENT = 'CREATE_CLIENT',
  UPDATE_CLIENT = 'UPDATE_CLIENT',
  GET_CLIENT = 'GET_CLIENT',
  GET_CLIENT_ARCHIVED = 'GET_CLIENT_ARCHIVED',
  UPDATE_CLIENT_ARCHIVED = 'UPDATE_CLIENT_ARCHIVED',
}

export default ClientPermission;
