enum RolesPermission {
  GET_ROLE = 'GET_ROLE',
  GET_ROLES = 'GET_ROLES',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  GET_ROLE_ARCHIVED = 'GET_ROLE_ARCHIVED',
  UPDATE_ROLE_ARCHIVED = 'UPDATE_ROLE_ARCHIVED',
}

export default RolesPermission;
