enum UserPermission {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  GET_USER = 'GET_USER',
  GET_USER_ARCHIVED = 'GET_USER_ARCHIVED',
  UPDATE_USER_ARCHIVED = 'UPDATE_USER_ARCHIVED',
}

export default UserPermission;
